language: php

php:
  - 5.6
  - 7.0
  - 7.1

before_script:
  - composer self-update
  - composer require 'cakephp/cakephp-codesniffer:dev-master'

script:
  - vendor/bin/phpcs -n -p --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP src/ config/

notifications:
  email: false
